// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.geek.grpc.lib.hello;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string code = 1;</code>
   */
  java.lang.String getCode();
  /**
   * <code>optional string code = 1;</code>
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>optional string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
